# -*- coding: utf-8 -*-
"""QnA demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgQ1_M55iuZ_Y9e4-yGw2RWe6AfXtgC6
"""

# !pip install allennlp
!pip install allennlp==1.0.0 allennlp-models==1.0.0

from allennlp.predictors.predictor import Predictor
## Old Model commented
# predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz")
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bidaf-model-2020.03.19.tar.gz")

passage = """
Ada brought a short note to Irene.David and Lucy walk one mile to go to school every day at 8:00AM when there is no snow.
"""

result=predictor.predict(
  passage=passage,
  question= "Who brought the note?"
  
  
)
result['best_span_str']

result=predictor.predict(
  passage=passage,
  question= "When do David and Lucy walk to school?"
  
  
)
result['best_span_str']